federation_version: 2
subgraphs:
  accounts:
    routing_url: http://localhost:80
    schema:
      subgraph_url: http://localhost:80
  reviews:
    routing_url: http://localhost:82
    schema:
      subgraph_url: http://localhost:82